name: Atualizar Dados Semanalmente

on:
  schedule:
    # Executa toda segunda-feira às 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Permite execução manual

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Extrair dados atualizados
        run: |
          mkdir -p data
          python -c "import goal500; goal500.get_player_stats().to_csv('data/player_stats.csv', index=False)"
          
      - name: Gerar visualização
        run: |
          mkdir -p images
          python -c "import goal500; import pandas as pd; goal500.plot_cumulative_goals(pd.read_csv('data/player_stats.csv'), 'images/cumulative_goals.png')"
          
      - name: Gerar animação
        run: |
          python -c "import goal500; import pandas as pd; goal500.create_animation(pd.read_csv('data/player_stats.csv'), 'images/cumulative_goals.gif')"
          
      - name: Commit e push das alterações
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/player_stats.csv images/cumulative_goals.png images/cumulative_goals.gif
          git commit -m "Atualização semanal de dados [skip ci]" || echo "Sem alterações para commit"
          git push
